version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "lockfile-only"
    commit-message:
      prefix: "test(dev)"
    open-pull-requests-limit: 0