version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "lockfile-only"
    commit-message:
      prefix: "chore(deps)"
    target-branch: "dev"