version: 2
updates:
  - package-ecosystem: "npm"
    directories: 
      - "/client/gmm-fe/"
      - "/server/gmm-api/"
      - "/server/directus/"
    schedule:
      interval: "daily"
    versioning-strategy: "lockfile-only"
    commit-message:
      prefix: "chore(deps)"
    target-branch: "dev"